syn match Statement "\v●.+$"
syn match Directory "\vExpected:.+$"
syn match WarningMsg "\vReceived:.+$"
syn match CocListFgRed "console.error"
syn match DiffDelete "\c\vFAIL ((\/|\\|\/\/)?[a-z0-9_@\-^!#$%&+={}.\/\\\[\]]+)+\.(js|tsx|ts)(:\d+:\d+)?"
syn match DiffAdd "\c\vPASS ((\/|\\|\/\/)?[a-z0-9_@\-^!#$%&+={}.\/\\\[\]]+)+\.(js|tsx|ts)(:\d+:\d+)?"
syn match DiffDelete "✕"
syn match DiffAdd "✓"
syn match Whitespace "\v\s+at .+ \(.+\)"
