hi! default link typescriptIdentifierName Structure
hi! default link typescriptExport Folded
hi! default link typescriptImport Folded
hi! default link typescriptDefault Folded
hi! default link typescriptVariable Folded
hi! default link jsClassKeyword Folded
hi! default link jsExtendsKeyword Folded
hi! default link tsxAttrib Folded
hi! default link typescriptFuncCallArg Folded
hi! default link typescriptStatementKeyword Conditional
hi! default link typescriptArrowFunc Conditional
